[build-system]
build-backend = "cmeel"
requires = [
  "cmeel[build]",
  "cmeel-eigen",
  "nanobind",
  "numpy>=2.0",
  "pytest",
  "scipy",
]

[project]
dependencies = [
  "numpy>=2.0",
]
description = "A support library for bindings between Eigen in C++ and Python, based on nanobind"
license = "BSD-3-Clause"
name = "nanoeigenpy"
requires-python = ">= 3.10"
version = "0.5.0"

[project.urls]
homepage = "https://github.com/cmake-wheel/nanobind"
repository = "https://github.com/cmake-wheel/nanobind.git"
upstream = "https://github.com/simple-robotics/nanobind"

[tool.tomlsort]
all = true
